### ISSUE TITLE
Current status

### ISSUE THREAD

**Issue by anaibol** [mikepugh/trackjs-node#2]
Hi, is this an official TrackJs client for node? Getting from npm returns error.

![selection_050](https://cloud.githubusercontent.com/assets/3210177/15247881/41ff6abe-1917-11e6-9f06-192765cc5f67.png)

**Comment by mikepugh** [comment]
Hi, no this is not an official client. I developed this as a prototype/proof of concept for my own use, and I shared with the TrackJS team but the last thing I heard from them (many months ago) was their priority and focus is on the browser client. 

I wouldn't recommend using this in any production scenario since it makes some assumptions about the payload that may or may not still be valid. I haven't looked at this code in a while.

I'll update the readme to get rid of the npm install line, that was all just there to make the repo easier for them to fork and take over.

**Comment by anaibol** [comment]
Thanks for the answer :)
@toddhgardner please release a node client! It think it should be a proprity since it's essential not only for backend javascript, but for tracking errors in universal / isomophic apps!

**Comment by toddhgardner** [comment]
Hey @anaibol, this is absolutely something we want to do, I'll add your comments to our request log :)

**Comment by anaibol** [comment]
Great!
